### ISSUE TITLE
Thank you, I found an API key in the wild. :D

### ISSUE THREAD

**Issue by GitHelge** [LiubovRukhlina/multistep-register-flow#3]
I'd recommend to add a TODO: Store in Environment Variables. ;-)

https://github.com/LiubovRukhlina/multistep-register-flow/blob/fca76fb6ed93c7615b87980796654e877163e54c/pages/api/cars.ts#L30

**Comment by GitHelge** [comment]
Normally you won't ship a key to a public repo but I mean its fine in this case, haha. 👍

**Comment by LiubovRukhlina** [comment]
fixed in https://github.com/LiubovRukhlina/multistep-register-flow/pull/4/commits/4f46126f911ea3f92a84d413f0a6726ed364f5fd
